### ISSUE TITLE
blur of texts

### ISSUE THREAD

**Issue by fabio21** [jnschulze/flutter-webview-windows#10]
blur of texts when we add the webview but it doesn't always happen

![Captura de tela 2021-05-20 130554](https://user-images.githubusercontent.com/8049768/119012657-9a398700-b96c-11eb-9807-2b4c99793e16.png)

**Comment by fabio21** [comment]
webview and only the image the rest and normal widgets

**Comment by jnschulze** [comment]
Hi,
sounds like https://github.com/flutter/flutter/issues/78648
Is your Flutter engine up to date?
