### ISSUE TITLE
HTML-Select tags not functional

### ISSUE THREAD

**Issue by Spitzbua** [jnschulze/flutter-webview-windows#100]
First of all thank you for your big effort on this plugin!

During testing, I noticed that the [selects ](https://www.w3schools.com/tags/tag_select.asp)are not functional. No menu opens. If the select is focused, it can be selected with the arrow keys. The option selection is not visible.

Do you know where the problem could lie here or at which point one starts to analyse?

**Comment by Spitzbua** [comment]
This issue is already known (https://github.com/MicrosoftEdge/WebView2Feedback/issues/1693) and they released a fix for that.

**Comment by vorte** [comment]
This is still an issue.

I can reproduce this on flutter 3.3.7 with webview-windows 0.2.2.

**Comment by yubnxd** [comment]
I also encountered this problem, is there any solution?
