### ISSUE TITLE
When running included example getting Error - Cannot open include file: 'atlstr.h'

### ISSUE THREAD

**Issue by chaudharydeepanshu** [jnschulze/flutter-webview-windows#101]
Getting this error when trying to run the example:-

> Launching lib\main.dart on Windows in debug mode...
> Building Windows application...
> Nuget is not installed.
> Attempting to download nuget.
> C:\Users\deepa\StudioProjects\flutter-webview-windows\example\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview.cc(3,10): fatal error C1083: Cannot open include file: 'atlstr.h': No such file or directory [C:\Users\deepa\StudioProjects\flutter-webview-windows\example\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
> Exception: Build process failed.

Following configuration of Visual Studio 2019 I'm using:-
![image](https://user-images.githubusercontent.com/85361211/155678065-b1828bb5-065a-4b59-a521-63e36a84754c.png)

I tried ```flutter clean```, deleting the windows folder, and recreating using ```flutter create .``` but nothing worked.
So is there any way to fix this?

**Comment by JacobDeuchert** [comment]
Looks like you are missing some dependencies. Does the file atlstr.h exist under the Path;
` C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\atlmfc\include` ?

You might need to install the C++ ATL Package to get it to work.
My installed Packages (Sorry for the screenshot language but you can just look at the numbers):
![image](https://user-images.githubusercontent.com/43518397/155810234-53fc15ae-9298-4911-a5ac-22639ef03d5d.png)

**Comment by chaudharydeepanshu** [comment]
Thanks, @JacobDeuchert adding the package "C++ ATL for latest build tools" fixed the issue.

You are right, before installing this package ```atlmfc``` folder was not present in ```C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\``` but installing this package created this folder there.
