### ISSUE TITLE
js 获取到postmessage 发送的内容 中文乱码

### ISSUE THREAD

**Issue by githupKing** [jnschulze/flutter-webview-windows#103]
js 获取到postmessage 发送的内容 中文乱码

**Comment by luyanggao** [comment]
I have the same problem.

**Comment by luyanggao** [comment]
先遍历map中的中文，用Uri.encodeFull处理下 再json.encode(map), 等js获取到后再解码需要的中文。

**Comment by yrmatou** [comment]
> 先遍历map中的中文，用Uri.encodeFull处理下 再json.encode(map), 等js获取到后再解码需要的中文。

您遇到过 h5里面 区域内下拉失效吗
