### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Eerey** [jnschulze/flutter-webview-windows#105]
Whenever I try to launch my app with this plugin, many errors like this appear and it crashes in the end (see stacktrace below).
What can I do?

`
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\flutter-projects\examplewebview\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]       
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: Das Löschen einer abstrakten Klasse "winrt::impl::implements_delegate<winrt::Windows::UI::Core::DispatchedHandler,H>" mit einem nicht virtuellen Destruktor führt zu einem nicht definierten Verhalten. [C:\flutter-projects\examplewebview\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\flutter-projects\examplewebview\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]       
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: Das Löschen einer abstrakten Klasse "winrt::impl::implements_delegate<winrt::Windows::UI::Core::DispatchedHandler,H>" mit einem nicht virtuellen Destruktor führt zu einem nicht definierten Verhalten. [C:\flutter-projects\examplewebview\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\flutter-projects\examplewebview\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]       
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: Das Löschen einer abstrakten Klasse "winrt::impl::implements_delegate<winrt::Windows::UI::Core::DispatchedHandler,H>" mit einem nicht virtuellen Destruktor führt zu einem nicht definierten Verhalten. [C:\flutter-projects\examplewebview\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\flutter-projects\examplewebview\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]       
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: Das Löschen einer abstrakten Klasse "winrt::impl::implements_delegate<winrt::Windows::UI::Core::DispatchedHandler,H>" mit einem nicht virtuellen Destruktor führt zu einem nicht definierten Verhalten. [C:\flutter-projects\examplewebview\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\flutter-projects\examplewebview\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]       
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: Das Löschen einer abstrakten Klasse "winrt::impl::implements_delegate<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool,winrt::Windows::Foundation::IInspectable>,H>" mit einem nicht virtuellen Destruktor führt zu einem nicht definierten Verhalten. [C:\flutter-projects\examplewebview\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: Das Löschen einer abstrakten Klasse "winrt::impl::implements_delegate<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Graphics::Capture::GraphicsCaptureItem,winrt::Windows::Foundation::IInspectable>,H>" mit einem nicht virtuellen Destruktor führt zu einem nicht definierten Verhalten. [C:\flutter-projects\examplewebview\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
Exception: Build process failed.
Exited (sigterm)
`

[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1526], locale de-DE)
    • Flutter version 2.10.3 at C:\flutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30204.135
    • Windows 10 SDK version 10.0.18362.0

[√] VS Code, 64-bit edition (version 1.64.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by jnschulze** [comment]
Your Windows SDK version (10.0.18362.0) is too old.

**Comment by Eerey** [comment]
Thank you, I will try updating it.

**Comment by Eerey** [comment]
Thanks @jnschulze it worked, however, I needed to upgrade to Windows 11 SDK in order to get a higher version.
