### ISSUE TITLE
Example error on first build

### ISSUE THREAD

**Issue by tranvanphay** [jnschulze/flutter-webview-windows#11]
I have run your example for testing, but it is error on first build. Please help me
![Capture](https://user-images.githubusercontent.com/42576241/119858146-63500c00-bf3e-11eb-9b5a-d9234580bd98.PNG)

**Comment by jnschulze** [comment]
Hi, please download nuget from https://www.nuget.org/downloads and add the containing directory to the `$PATH` enviroment variable.

**Comment by tranvanphay** [comment]
> Hi, please download nuget from https://www.nuget.org/downloads and add the containing directory to the `$PATH` enviroment variable.
Yes, I have install nuget and add to the `$PATH`, and it is another error
![image](https://user-images.githubusercontent.com/42576241/119861576-be373280-bf41-11eb-856e-a1a0658fbcdc.png)

**Comment by jnschulze** [comment]
Try to delete the build directory / run `flutter clean` to force redownloading the Webview2 SDK.

**Comment by tranvanphay** [comment]
> Try to delete the build directory / run `flutter clean` to force redownloading the Webview2 SDK.

Oh, It's still error same above

**Comment by jnschulze** [comment]
Does `WebView2.h` exist in `example/build/windows/packages/Microsoft.Web.WebView2/build/native/include`?

**Comment by tranvanphay** [comment]
> Does `WebView2.h` exist in `example/build/windows/packages/Microsoft.Web.WebView2/build/native/include`?
In my case, it is have not folder packages on build/windows
![image](https://user-images.githubusercontent.com/42576241/120127110-a7fed000-c1e8-11eb-9e29-6383dbc9a702.png)

**Comment by tranvanphay** [comment]
> Does `WebView2.h` exist in `example/build/windows/packages/Microsoft.Web.WebView2/build/native/include`?
I have successfully on build. Just need install this MSVC version.
![image](https://user-images.githubusercontent.com/42576241/120139237-3df32480-c202-11eb-84e5-36ec33734636.png)

**Comment by CodingWithTashi** [comment]
Can anyone help me with this I am getting same error i.e fatal error C1083: Cannot open include file: 'WebView2.h': No such file or directory. I have added msvc as well. @jnschulze  @tranvanphay

**Comment by CodingWithTashi** [comment]
if anyone facing any issue with desktop build with visual studio 2019, make sure you have `visual studio redistributable` as well.
Link here: https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

Thanks for great package
