### ISSUE TITLE
Is there any way to excute document.getElementById("myVideo") from HTML by using Flutter?

### ISSUE THREAD

**Issue by Thinhvo-tech** [jnschulze/flutter-webview-windows#110]
If you have an example. Please help me. Thank you!

**Comment by Thinhvo-tech** [comment]
I mean that execute play video from flutter
![image](https://user-images.githubusercontent.com/74093060/158284932-1b5b3d07-b5c0-4e1c-b516-f9ab3dc4e315.png)

**Comment by Thinhvo-tech** [comment]
_winController.loadingState.listen((event) async {
      if (event == LoadingState.navigationCompleted) {
        await _winController.executeScript(
            "window.chrome.webview.postMessage(window.document.getElementById('clickVideo').play())");
      }

**Comment by jnschulze** [comment]
Looks like you‘ve found your solution.

**Comment by Thinhvo-tech** [comment]
Yeah, I've find the solution for my project. Thank you for your plugin

**Comment by Thinhvo-tech** [comment]
Yeah, I've find the solution for my project. Thank you for your plugin

**Comment by Thinhvo-tech** [comment]
Can you help me with windows flutter?

 When I am install and doubleclick app which doesn't running on my
computer.

I appreciated!
