### ISSUE TITLE
WebView not working correct when using Touchscreen

### ISSUE THREAD

**Issue by brownson** [jnschulze/flutter-webview-windows#111]
WebView does not work properly when using a touch screen. When attempting to scroll with a touchscreen, text is marked selected instead of scrolling. Executing a button doesn't work either.

The issue can be reproduced using the sample app on a touchscreen.

**Comment by rasphlat** [comment]
Same issue here, the scrolling is not working with a Windows device using the touch screen

**Comment by lukas-rapp** [comment]
Same issue here... Is there a solution so far?

**Comment by maciola** [comment]
We have the same experience here - We try to port our existing cordova windows app to flutter. It seems that touch/pointer events are not passed while your using touch screen. The mouse events (expect wheel scrolling) work fine.
We are looking forward for a solution.

**Comment by CyberiaSoft** [comment]
Same issue here...
