### ISSUE TITLE
environment_creation_failed

### ISSUE THREAD

**Issue by luyanggao** [jnschulze/flutter-webview-windows#112]
help!    when i build release and run .exe   on win10家庭中文版20H2.

**Comment by jnschulze** [comment]
Does it fail in release mode only?

**Comment by luyanggao** [comment]
Thanks.
Neither can debug.
I copy debug and release to a new computer without a flutter environment, and then prompt the error.
What should I do？

**Comment by jnschulze** [comment]
Install the WebView2 runtime.

**Comment by luyanggao** [comment]
Is it possible to package the WebView2 runtime into an release package for all customers to use?

**Comment by jnschulze** [comment]
Sure, you need to create a proper installer. But this is beyond the scope of this plugin.
