### ISSUE TITLE
Running error | Deleting an abstract class "winrt::impl::implements_delegate<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Graphics::Capture::GraphicsCaptureItem,winrt::Windows::Foundation::IInspectable> 'H>' with a non-virtual destructor results in undefined behavior.

### ISSUE THREAD

**Issue by Thoxh** [jnschulze/flutter-webview-windows#113]
Hey there, I just added webview to my dependencies and added nuget to my path but since the implementation (just in pubspec not in code so far) of webview I'm getting following error when running my code:

Translated: Deleting an abstract class "winrt::impl::implements_delegate<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Graphics::Capture::GraphicsCaptureItem,winrt::Windows::Foundation::IInspectable> 'H>' with a non-virtual destructor results in undefined behavior.

Full error:
`Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
[C:\Program]() Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: Die folgende Warnung wird als Fehler behandelt. [[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
[C:\Program]() Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: Das Löschen einer abstrakten Klasse "winrt::impl::implements_delegate<winrt::Windows::UI::Core::DispatchedHandler,H>" mit einem nicht virtuellen Destruktor führt zu einem nicht definierten Verhalten. [[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
[C:\Program]() Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: Die folgende Warnung wird als Fehler behandelt. [[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
[C:\Program]() Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: Das Löschen einer abstrakten Klasse "winrt::impl::implements_delegate<winrt::Windows::UI::Core::DispatchedHandler,H>" mit einem nicht virtuellen Destruktor führt zu einem nicht definierten Verhalten. [[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
[C:\Program]() Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: Die folgende Warnung wird als Fehler behandelt. [[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
[C:\Program]() Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: Das Löschen einer abstrakten Klasse "winrt::impl::implements_delegate<winrt::Windows::UI::Core::DispatchedHandler,H>" mit einem nicht virtuellen Destruktor führt zu einem nicht definierten Verhalten. [[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
[C:\Program]() Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: Die folgende Warnung wird als Fehler behandelt. [[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
[C:\Program]() Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: Das Löschen einer abstrakten Klasse "winrt::impl::implements_delegate<winrt::Windows::UI::Core::DispatchedHandler,H>" mit einem nicht virtuellen Destruktor führt zu einem nicht definierten Verhalten. [[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
[C:\Program]() Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: Die folgende Warnung wird als Fehler behandelt. [[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
[C:\Program]() Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: Das Löschen einer abstrakten Klasse "winrt::impl::implements_delegate<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool,winrt::Windows::Foundation::IInspectable>,H>" mit einem nicht virtuellen Destruktor führt zu einem nicht definierten Verhalten. [[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
[C:\Program]() Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: Das Löschen einer abstrakten Klasse "winrt::impl::implements_delegate<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Graphics::Capture::GraphicsCaptureItem,winrt::Windows::Foundation::IInspectable>,H>" mit einem nicht virtuellen Destruktor führt zu einem nicht definierten Verhalten. [[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\texture_bridge_fallback.cc(53,24): error C2039: "release_context" ist kein Member von "FlutterDesktopPixelBuffer". [[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\texture_bridge_fallback.cc(56,24): error C2039: "release_callback" ist kein Member von "FlutterDesktopPixelBuffer". [[C:\Users\Z0115791\Desktop\Digital]() Production\FlutterProjects\Labor\labor\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
Exception: Build process failed.
Exited (sigterm)`

**Comment by jnschulze** [comment]
See #105
