### ISSUE TITLE
App Crashes on Windows

### ISSUE THREAD

**Issue by matteotoma98** [jnschulze/flutter-webview-windows#114]
webview_windows_plugin.dll make crashes my app only on certain Windows.
I insalled webview2 and windows version is more than Windows 10 1809+.
Any idea?
EDIT: Its seem that depends on build and version of windows. For example on windows 10 home version 21h2 app crashes. In windows 11 or windows 10 (version 10.0.18363 build 18363) doesn't crash.

**Comment by jnschulze** [comment]
What’s your definition of „crash“?
How can this be reproduced?
What makes you conclude that it‘s related to the Windows version? How many machines did you try? Is there a stack trace available?

**Comment by matteotoma98** [comment]
![Immagine](https://user-images.githubusercontent.com/48352371/159139311-73b9a8e4-d138-43e7-b0ee-81a914c55f9e.png)
This is the info on windows event viewer of the app that crashes (i mean that it autocloses while is opening).
I tested the app on window 11 and didn't crashed, windows 10 version 10.0.18363, but it seems crashing on window 10 21h1/h2 build....

**Comment by jnschulze** [comment]
When does it crash? (right after Startup, upon opening a specific website, when terminating the app, resizing the window etc.)?

**Comment by matteotoma98** [comment]
While opening the app, on home, even before using the service that use your plugin for windowd web view, the windows spinner loading and after 3-4 seconds it crashes with the error on the screenshot i posted.
This happens also running app as admin, or any type of compatibility. I'm pretty sure that the dll generated by flutter have problems with older version of Windows...

**Comment by rasphlat** [comment]
![Cattura](https://user-images.githubusercontent.com/30881307/159451537-1f550edd-5dbd-48d6-b366-ac60069c05f0.PNG)
I have the same problem, the app crashes before starting. I have this issue on windows 21H1 and 21H2 versions

**Comment by cacard** [comment]
me too, crash after init.

**Comment by jnschulze** [comment]
0xc000001d means bad instruction. Do you CPUs lack AVX2 support?
Try commenting out https://github.com/jnschulze/flutter-webview-windows/blob/3a7f8cfaa5863c7b937a846f89c2744ed6e0ae9a/windows/CMakeLists.txt#L69

**Comment by iulian0512** [comment]
> 0xc000001d means bad instruction. Do your CPUs lack AVX2 support? Try commenting out
> 
> https://github.com/jnschulze/flutter-webview-windows/blob/3a7f8cfaa5863c7b937a846f89c2744ed6e0ae9a/windows/CMakeLists.txt#L69

@jnschulze many thanks for providing this workaround.
 do you know if there are any issues compiling and running without this cpu extension enabled?

**Comment by jnschulze** [comment]
> > 0xc000001d means bad instruction. Do your CPUs lack AVX2 support? Try commenting out
> > https://github.com/jnschulze/flutter-webview-windows/blob/3a7f8cfaa5863c7b937a846f89c2744ed6e0ae9a/windows/CMakeLists.txt#L69
> 
> @jnschulze many thanks for providing this workaround. do you know if there are any issues compiling and running without this cpu extension enabled?

This workaround increases CPU usage. However, as of version 0.2.2, it should not even be necessary anymore as it uses a different texture interface that newer Flutter engines provide.
