### ISSUE TITLE
Getting value of inner html from webview into dart (as a string). 

### ISSUE THREAD

**Issue by Ingenious-c0der** [jnschulze/flutter-webview-windows#115]
Hello,
 ## Is there a way in which I can get the value of a text element in the web page (self-hosted) as a dart String?

So far I have only found executeScript which returns Future<void> thereby making it incapable of doing this. Also, there isn't a Javascript channel like what we have in webview_flutter (for IOS and Android) which could also facilitate this two-way communication. 
Thanks in advance.

**Comment by jnschulze** [comment]
Use `window.chrome.webview.postMessage` for posting a message back to Dart.

**Comment by Ingenious-c0der** [comment]
Thank you for the prompt response, but how would I go about listening to this message from Dart side? Could you please provide a small example / link.

**Comment by jnschulze** [comment]
Being an „ingenious c0der“, you will find out yourself.
Hint: Take a look at the `WebviewController`

**Comment by Ingenious-c0der** [comment]
I have had a look at all the methods available under `Webview Controller`. Nonetheless, I will dive in deeper once again since you are suggesting that I am missing something obvious. Thank you for the help .

**Comment by jnschulze** [comment]
> I have had a look at all the methods available under `Webview Controller`. Nonetheless, I will dive in deeper once again since you are suggesting that I am missing something obvious. Thank you for the help .

I was just kidding. `WebviewController.webMessage` is a stream for listening to messages.
