### ISSUE TITLE
Strange screen tearing effects on PDF files and videos.

### ISSUE THREAD

**Issue by ckruppe** [jnschulze/flutter-webview-windows#121]
Loading an video file in the webview or showing an pdf results in heavy screen tearing effects.

https://user-images.githubusercontent.com/17411150/164008935-840521e5-d0b7-4cee-8fca-f7fd836b9895.mp4

**Comment by alexcode9** [comment]
Same using Chart.js

**Comment by jnschulze** [comment]
Does it still occur with the latest versions of both the plugin and the WebView2 runtime?
