### ISSUE TITLE
When will the merged #102 PR be released?

### ISSUE THREAD

**Issue by gmuehlenberg** [jnschulze/flutter-webview-windows#123]
Hi! So I wanted to use the flutter-webview-windows for a work project. But we desperately need the browser console. There is the PR #102 which added this feature to this project. But it's not released, not even as a prerelease. Please, when will a new update come?

**Comment by gmuehlenberg** [comment]
Closing this: There has been a merged PR for this: https://github.com/jnschulze/flutter-webview-windows/pull/102

**Comment by gmuehlenberg** [comment]
Reopen: The merged PR #102 has no release version. So we cannot open the Devtools.

**Comment by jnschulze** [comment]
I've just published version `0.1.7`.
