### ISSUE TITLE
why app crashed when open web view?

### ISSUE THREAD

**Issue by majidebraa** [jnschulze/flutter-webview-windows#125]
Hello.
I embed webview2 runtime in my project and prompt to install it with the Inno setup compiler. it's ok on my system but when I try to open web view in another windows system it's crashed. 
windows 10 
support avx2
![cpu-z-](https://user-images.githubusercontent.com/82038698/166095452-22086e6f-7347-47bf-b835-38b3344bcb96.png)

Event Viewer Error:

Faulting application name: herman.exe, version: 1.0.0.0, time stamp: 0x6266688a
Faulting module name: ucrtbase.dll, version: 10.0.17134.677, time stamp: 0x9f346d3f
Exception code: 0xc0000409
Fault offset: 0x000000000006e14e
Faulting process id: 0x1fe4
Faulting application start time: 0x01d85c55e164f073
Faulting application path: C:\Program Files (x86)\Herman\herman.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: d6b6766e-9f7e-4f62-8048-ff60c6a23d5d
Faulting package full name:

**Comment by hanguanxian** [comment]
the same problems as me @majidebraa

**Comment by jnschulze** [comment]
Can‘t reproduce this. Feel free to reopen if this still happens with the latest versions of this plugin and Flutter.

**Comment by jatech1** [comment]
Did anyone ever find a solution for this?  I have the same issue.
