### ISSUE TITLE
loadStringContent can not load local image

### ISSUE THREAD

**Issue by Xiangjinxiu** [jnschulze/flutter-webview-windows#130]
https://user-images.githubusercontent.com/19357819/167236980-c5be9e9d-2e17-4f51-969f-9500b39f4f18.png
I use loadUrl(getAssetFileUrl('assets/test.html')) it work the image show
but when use loadStringContent(html) the image doesn,t show
I want to use loadStringContent how to fix this problem

**Comment by Xiangjinxiu** [comment]
![image](https://user-images.githubusercontent.com/19357819/167242825-c9c3559b-3af8-435e-ab8c-91181df00be9.png)

**Comment by jnschulze** [comment]
`loadStringContent` uses WebView’s `NavigateToString` which internally sets the current URL to `about:blank`. For security reasons, however, it’s not possible to access local files then.

WebView2 supports mapping a local directory to a fake domain (SetVirtualHostNameToFolderMapping), however, it’s not supported by this plugin yet.

**Comment by Xiangjinxiu** [comment]
![ec1d70f3d26655d80fba8329fd2c055](https://user-images.githubusercontent.com/19357819/167249965-ada21106-cf9b-4928-91c6-15f41e1e8246.png)
ok， thank you！
