### ISSUE TITLE
The dropdown selection in the WebView is not working

### ISSUE THREAD

**Issue by Yosuke-li** [jnschulze/flutter-webview-windows#138]
https://user-images.githubusercontent.com/36600238/169186673-9f516649-979d-4c36-a18e-a510079a094c.mov

look this video.how to fix it? Thanks

**Comment by angle222** [comment]
the same problems as me @jnschulze

**Comment by Spitzbua** [comment]
I have a slightly different behaviour. The menu list does not open when clicking on the arrow and no selection can be made. I thought the issue is fixed with new Webview2 sdk version https://github.com/MicrosoftEdge/WebView2Feedback/issues/1693

**Comment by hydev777** [comment]
I have the same issue that @Spitzbua has, whenever I clicked a dropdown it does not open.

**Comment by Dobariyakishan** [comment]
any update on this issue??

**Comment by rubencscas** [comment]
I also have the same problem. Anyone has solved this problem?

**Comment by njuptzwt** [comment]
I also have the same problem. Any solution?

**Comment by masmilondev** [comment]
I also have the same problem. Any solution?

**Comment by yagnesh1406** [comment]
I am facing the same issue.

**Comment by LukasSkywalker** [comment]
I switched to https://github.com/jakky1/webview_win_floating because of this issue. With WebviewWinFloating, everything works.
