### ISSUE TITLE
Not support high dpi

### ISSUE THREAD

**Issue by yisar** [jnschulze/flutter-webview-windows#141]
![62622935b2ed18107556ff455897d19](https://user-images.githubusercontent.com/12951461/169697059-e2f2d058-17c6-43c7-aa80-a8d3a6326a75.png)

**Comment by yisar** [comment]
@jnschulze Any progress？

**Comment by lycstar** [comment]
请问高分辨率模糊的问题解决了吗

**Comment by stevenBang** [comment]
沒解決
我改用Electron開發

Cc ***@***.***> 於 2022年10月14日 週五 上午8:30寫道：
