### ISSUE TITLE
Webview2 headers not found unless flutter build is run twice

### ISSUE THREAD

**Issue by emsaints** [jnschulze/flutter-webview-windows#144]
Thanks for a great package, it's indispensable for Flutter right now.

I'd like to use the latest version with the runtime AVX detection, however I'm running into the "missing Webview2.h" issue, which resolves when I run the flutter build again. So after a `flutter clean`, the first `flutter build` fails, and the next `flutter build` succeeds.

Visual Studio 2022 Community 17.2.2
Flutter 3.0.1
webview_windows 0.1.9

<img width="1435" alt="Screen Shot 2022-05-26 at 12 10 27 AM" src="https://user-images.githubusercontent.com/3943854/170437426-ecbba2cb-a804-4990-96a3-e6b207b60033.png">

**Comment by jnschulze** [comment]
I‘m unable to reproduce this.
