### ISSUE TITLE
error C2039 'release_context', 'release_callback'

### ISSUE THREAD

**Issue by Munhun** [jnschulze/flutter-webview-windows#145]
flutter-webview-windows-main\example\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\texture_bridge_fallback.cc(53,40): error C2039: 'release_context': It is not member of 'FlutterDesktopPixelBuffer' [~~~flutter-webview-windows-main\example\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]

flutter-webview-windows-main\example\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\texture_bridge_fallback.cc(56,41): error C2039: 'release_callback':  It is not member of 'FlutterDesktopPixelBuffer'  [~~~flutter-webview-windows-main\example\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]

Exception: Build process failed.

**Comment by jnschulze** [comment]
What’s your Flutter SDK version? It’s apparently older than version 2.8.0…
