### ISSUE TITLE
Why initialize 3 or 6 webview2 processes?

### ISSUE THREAD

**Issue by linming63** [jnschulze/flutter-webview-windows#153]
When I run App first time and initialize first webview,  there are 3 webview2 processes.
![3 webviews](https://user-images.githubusercontent.com/107540197/173779528-db025135-eaab-4d06-8786-be0766ea6123.jpg)

then run App again,  there are 6 webview2 processes.
![6 webviews](https://user-images.githubusercontent.com/107540197/173779854-d0ac83cb-893f-4a03-82e1-a4347f856204.jpg)

**Comment by jnschulze** [comment]
A single WebView2 instance will give you at least three processes (1 browser process, 1 or more renderer process(es) and at least one helper process).

> When I run App first time and initialize first webview, there are 3 webview2 processes. ![3 webviews](https://user-images.githubusercontent.com/107540197/173779528-db025135-eaab-4d06-8786-be0766ea6123.jpg)
> 
> then run App again, there are 6 webview2 processes. ![6 webviews](https://user-images.githubusercontent.com/107540197/173779854-d0ac83cb-893f-4a03-82e1-a4347f856204.jpg)

By "running again" you mean a hot restart? Does the number of processes increase every time you perform a hot restart?

**Comment by linming63** [comment]
thank you!
