### ISSUE TITLE
How to remove body padding on sample model

### ISSUE THREAD

**Issue by renanld** [jnschulze/flutter-webview-windows#159]
Hi,
I'm new at Flutter and I'm trying to develop an Windows App that connects to my local web server.
And I did that following the sample app.

But I can't remove de boddy padding (see in the attached image)
could someone help me?
Thanks! 

![Untitled-1](https://user-images.githubusercontent.com/99410495/175773227-5e28d026-d3e3-4db5-9c30-d868888506c8.jpg)

**Comment by Ingenious-c0der** [comment]
Can you post the code here for that widget/screen?

**Comment by venky9885** [comment]
``
Widget compositeView() {
    if (!_controller.value.isInitialized) {
      return const Text(
        'Not Initialized',
        style: TextStyle(
          fontSize: 24.0,
          fontWeight: FontWeight.w900,
        ),
      );
    } else {
      return Padding(
        padding: EdgeInsets.all(20),

``
Remove  Last 2 lines in your code check ur code contains these 2 lines Padding(  padding: EdgeInsets.all(20),

**Comment by renanld** [comment]
@venky9885 solution works!
Thanks guys! :)
