### ISSUE TITLE
Error while sending data from webcontent to flutter.

### ISSUE THREAD

**Issue by CodingWithTashi** [jnschulze/flutter-webview-windows#17]
Hi @jnschulze , While I was trying to send data from webcontent to flutter I am getting following error.   
`Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<dynamic, String>'`   

Here is the codesnippet:   
In test.js file(trying to send json data):   
```
function myFunction() {
  var value = {"name":"tashi"}
  window.chrome.webview.postMessage(value);

}
```    
Now in main.dart (I have listener)   
```
_controller.webMessage.listen((event) {
      print(event);
    });
```   
when I run this code, I am getting error saying    `type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<dynamic, String>'`   
and error redirect me to this code in package   
```
 case 'webMessageReceived':
              try {
                final message = json.decode(map['value']);
                _webMessageStreamController.add(message);
              } catch (ex) {
                _webMessageStreamController.addError(ex);
              }
```   
I believe in `webviews_window.dart`  ` Stream<Map<dynamic, String>>` get webMessage should be  `Stream<Map<String, dynamic>>`
thanks for your help

**Comment by jnschulze** [comment]
> I believe in `webviews_window.dart` ` Stream<Map<dynamic, String>>` get webMessage should be `Stream<Map<String, dynamic>>`

Exactly, thanks. Should be fixed now.
