### ISSUE TITLE
MapView scroll to zoom in and zoom out does't work

### ISSUE THREAD

**Issue by tashi146** [jnschulze/flutter-webview-windows#174]
Hi, I am trying to load ESRI map in window_webview and it is working fine, but when I try to zoom and zoom out by scrolling, It doesn't work. I am using the latest version. Is there any method or widget like WebViewAware or how can we fix this?   

Thanks for awesome package

**Comment by tashi146** [comment]
I end up adding my own listener to flutter webview widget and handle the same in JavaScript content

**Comment by 7571deng** [comment]
> 



> I end up adding my own listener to flutter webview widget and handle the same in JavaScript content

Any code examples
