### ISSUE TITLE
Null safety error & "Not Initialized" on screen.

### ISSUE THREAD

**Issue by alexmercerind** [jnschulze/flutter-webview-windows#18]
Hi there!
I've been trying to get this plugin to work but cannot.
I'm trying to build example app.

**Exception:**
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: LateInitializationError: Field '_methodChannel@18215898' has not been initialized.
#0      WebviewController._methodChannel (package:webview_windows/webview_windows.dart)
#1      WebviewController.loadUrl (package:webview_windows/webview_windows.dart:205:11)
#2      _MyAppState.initPlatformState (package:app/main.dart:39:23)
```

**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.572], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.6)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.56.2)
[✓] Connected device (3 available)
```

**Further information**
I'm on latest Windows SDK.

Thanks a lot. Please help me out. 🙏

**Comment by jnschulze** [comment]
Hi,
sorry for the inconvenience. The only reason I can think of is a PlatformException upon initializing the webview which isn't handled yet unfortunately. Therefore the 'late' methodChannel property stays uninitialized.

Maybe you could take a look at the exception here:

https://github.com/jnschulze/flutter-webview-windows/blob/9283edae449d5b2b12ed4062fc80e7602e384bf7/lib/webview_windows.dart#L228

I'd be happy to review a PR that improves the error handling ;)

**Comment by alexmercerind** [comment]
Hi @jnschulze !
I've been trying to dig up  find the cause in the C++ code, but unfortunately none of my `cout`s work. (Is there something that I'm missing?)
And this is the exception I get.
```
flutter: PlatformException(Creating Webview environment failed, null, null, null)
flutter: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:43)
<asynchronous suspension>
#3      WebviewController.initialize (package:webview_windows/webview_windows.dart:183:21)
<asynchronous suspension>
#4      _MyAppState.initPlatformState (package:webview_windows_example/main.dart:33:5)
<asynchronous suspension>
```

**Comment by jnschulze** [comment]
Looks like the [WebView2 runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) is missing on your machine.

**Comment by alexmercerind** [comment]
@jnschulze I just had no idea that its a dependency. Apologies.

**Comment by jnschulze** [comment]
The readme might not be clear enough about that dependency.
But I should make the plugin display a proper error message anyway and show a link that allows obtaining the runtime.

The reason I decided for WebView2 and against alternatives like CEF is that WW2 might get shipped with Windows sooner or later. But in order to prevent unnecessary bloat, I didn‘t want to automatically include the runtime either.

see https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

**Comment by jgoyvaerts** [comment]
Does this WebView2 runtime have to be installed on clients using the flutter app too, or only when compiling?
if yes, is there any way to include this in the flutter app itself?

**Comment by jnschulze** [comment]
> Does this WebView2 runtime have to be installed on clients using the flutter app too, or only when compiling?
> if yes, is there any way to include this in the flutter app itself?

Yes, it needs to be installed on client machines, too.
So you either need to adjust your app installer to ensure that the runtime is installed and/or add a mechanism to your app to install the runtime before creating a WebView instance (this should ideally be added to this plugin later on).
