### ISSUE TITLE
 how to execute javascript code in webview_windows

### ISSUE THREAD

**Issue by proalex1996** [jnschulze/flutter-webview-windows#184]
i need execute javascript code to get document HTML, 
I can't find any function in the library that can be used, please help me

**Comment by saber34bba** [comment]
any solution for this?

**Comment by pmah8** [comment]
I would like to this as well. Something similar to webview_flutter_plus where there is a "onWebViewCreated" callback where you can then use the controller to load an URl and execute something like 'document.documentElement.innerHTML' and get back the document string to parse.

**Comment by jnschulze** [comment]
Now that #167 has been merged, you can just invoke `controller.executeScript('document.documentElement.innerHTML')`. Note that you should subscribe to the loading state stream and wait for the document to be fully loaded.
