### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by nishchithnish** [jnschulze/flutter-webview-windows#20]
Getting this error

![image](https://user-images.githubusercontent.com/85146813/121856132-c6e58200-cd11-11eb-912f-b25bb682c806.png)

I have already tried running the example project as well as using the plugin in seperate new project. Recreated windows folers in flutter. Also tried `flutter clean`. Restarted dektop. 

My current setup

Webview run time
![image](https://user-images.githubusercontent.com/85146813/121856238-e7add780-cd11-11eb-86a0-610e24ca49f5.png)

Visual Studio
![image](https://user-images.githubusercontent.com/85146813/121856375-0f04a480-cd12-11eb-9dd8-ecdee9af2f3e.png)

Components
![image](https://user-images.githubusercontent.com/85146813/121856698-69056a00-cd12-11eb-8be2-498ff2b49007.png)

![image](https://user-images.githubusercontent.com/85146813/121856783-84707500-cd12-11eb-9720-c3b84254670a.png)

OS
![image](https://user-images.githubusercontent.com/85146813/121856868-9d792600-cd12-11eb-8b4d-a007be039de0.png)

**Comment by ce-muzzamil** [comment]
I am facing the same issue. have you found a solution?

**Comment by jnschulze** [comment]
Which version are you using? Did you have a look at other comments/issues?

- https://github.com/jnschulze/flutter-webview-windows/issues/11#issuecomment-851159588
- another comment: https://github.com/jnschulze/flutter-webview-windows/issues/11#issuecomment-859550015

Maybe it's a WebView2 issue (see https://github.com/MicrosoftEdge/WebView2Feedback/issues/1209)
Just try to specify another WebView version in `windows/CMakeLists.txt`

Or I forgot to list a dependency. As the example can be built using Github actions, you might want to take a look at what's included in the Github actions image: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

**Comment by ce-muzzamil** [comment]
Yes, after reading the other comments/issues, the problem is resolved. thank you so much for you efforts.
