### ISSUE TITLE
Blurred under the high-resolution big screen

### ISSUE THREAD

**Issue by lycstar** [jnschulze/flutter-webview-windows#200]
Is there a solution to this problem, thanks. @jnschulze

**Comment by lycstar** [comment]
@jnschulze hello
I found that the reason for blurring under high system scaling (>100%) may be.
![image](https://user-images.githubusercontent.com/37872392/196662383-8e61d95f-0c3f-4187-9dbe-5ae3048d6eba.png)
 I changed the code to 
![image](https://user-images.githubusercontent.com/37872392/196662762-062fa45d-0fb5-4430-a9a8-3a9be4f56eca.png)
it works fine.

same change in _setPointerButtonState and more methods.

Maybe you have a better way.

**Comment by lycstar** [comment]
@Doflatango

**Comment by Doflatango** [comment]
Yes, you may keep it as a temporary workaround, also I have a same workaround.
FYR: https://github.com/Doflatango/flutter-webview-windows/commit/d7a199e07e57339e36d8c9f4579666594dd5dcd2

**Comment by lycstar** [comment]
🐮🍺 @Doflatango

**Comment by lycstar** [comment]
You write very well. Thank you for your code. @Doflatango

**Comment by vorte** [comment]
I'm seeing the same. Can we raise a PR with the fix? @lycstar @Doflatango

**Comment by lycstar** [comment]
I'm waiting for @Doflatango PR.His code is great. @vorte

**Comment by Doflatango** [comment]
It's a  temporary workaround not a solution, it consumes more GPU, so I have no plans to make a PR. But if @jnschulze agrees to do so, I can open a PR for this.

**Comment by jnschulze** [comment]
> It's a temporary workaround not a solution, it consumes more GPU, so I have no plans to make a PR. But if @jnschulze agrees to do so, I can open a PR for this.

Sure, that would be great.
Resource usage will obviously be higher but there‘s nothing one could do I guess.

**Comment by Doflatango** [comment]
> Sure, that would be great. 
Resource usage will obviously be higher but there‘s nothing one could do I guess.

That's great!
I will open a PR ASAP.
