### ISSUE TITLE
Memory Management

### ISSUE THREAD

**Issue by vorte** [jnschulze/flutter-webview-windows#209]
It seems like the package is not releasing the webview processes correctly. When I start the app, I only have 1 process running. Then I open the webview screen and around 5/6 new processes are spawned (which is fine) including one Epub Reader process. 

However, every time I navigate away from the webview screen the processes remain running. Also every time I reopen the webview screen in the app, a new Epub Reader process is spawned and they seem to never be closed. They just keep running and so the app keeps consuming more and more memory.

Is there something I'm missing? Maybe a call to dispose of the webview cleanly.

<img width="670" alt="webview_windows" src="https://user-images.githubusercontent.com/2916166/201172708-6d3e9a35-b522-49ad-868f-2be73e83a48a.png">

**Comment by jnschulze** [comment]
Do you dispose the `WebviewController`?

**Comment by vorte** [comment]
Thanks, that was the missing piece. 👍 I would recommend updating the example though.
