### ISSUE TITLE
Camera permission is asked every time I open the access camera

### ISSUE THREAD

**Issue by CodingWithTashi** [jnschulze/flutter-webview-windows#217]
Thanks for great plugin, I having issue while accessing camera from webview. I have this code in my application to access camera

```
 return Webview(
                controller,
                permissionRequested: (url, permissionKind, isUserInitiated) =>
                    _onPermissionRequested(
                  url: url,
                  kind: permissionKind,
                  isUserInitiated: isUserInitiated,
                  context: context,
                  isPermissionGranted: isPermissionGranted,
                ),
              );
```
This code work fine but every time I run this code it is asking for camera permission even if grant the permission.

**Comment by jnschulze** [comment]
So it keeps asking per request? I haven’t found any documentation on how long a permission, once granted, is considered valid. Can’t you just cache the user’s decision?

**Comment by CodingWithTashi** [comment]
@jnschulze  I tried to cache but It didn't work, when I allow the permission request  for first time and try to open camera it is not opening unless I ask the permission again.

**Comment by alnaum** [comment]
@CodingWithTashi Have you found a solution?

**Comment by CodingWithTashi** [comment]
This issue can be fixed within the application it self. In my case, I have fixed it within my packages. If you are interested only with permission, do check this out this [PR](https://github.com/CodingWithTashi/simple_barcode_scanner/pull/27/files#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25)
