### ISSUE TITLE
Question about webview2 version used

### ISSUE THREAD

**Issue by CJ9701** [jnschulze/flutter-webview-windows#218]
In file [CMakeLists.txt](https://github.com/jnschulze/flutter-webview-windows/blob/main/windows/CMakeLists.txt) is currently the WEBVIEW_VERSION 1.0.1210.39 defined.

When a client has a newer webview2 runtime installed than version 1.0.1210.39 will the newer version be used? I was wondering because we have a newer webview2 runtime installed but it seems features are missing.

For which cases the nuget package will be used?

Thank you for bringing clarity!

**Comment by jnschulze** [comment]
Hi,
the `WEBVIEW_VERSION` just defines the SDK version (which is taken from a nuget package). But during execution, it will always use the client’s WebView runtime DLLs.

Which features are you referring to?
