### ISSUE TITLE
Can it support MacOS?

### ISSUE THREAD

**Issue by iamjia** [jnschulze/flutter-webview-windows#223]

**Comment by gslender** [comment]
Would this package help with macOS support ??

https://github.com/mkoehnke/WKZombie

**Comment by iamjia** [comment]
> 

thank you

**Comment by jnschulze** [comment]
No, given that this library is backed by WebView2 which is Windows only atm (macOS support seems to be planned though https://github.com/MicrosoftEdge/WebView2Feedback/issues/1314)
