### ISSUE TITLE
Build windows failed

### ISSUE THREAD

**Issue by hushmand** [jnschulze/flutter-webview-windows#226]
After adding the flutter-webview-windows to app, the project does not build

I used flutter 3.3.9 and visual studio 2019

> flutter build windows 
💪 Building with sound null safety 💪
 C:\Users\template\Desktop\temp\winapp\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview_windows_plugin.cc(190,22): error C2039: 'format': is not a member of 'std' [C:\Users\template\Desktop\temp\winapp\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\template\Desktop\temp\winapp\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview_windows_plugin.cc(210,1): error C3861: 'format': identifier not found [C:\Users\template\Desktop\temp\winapp\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\template\Desktop\temp\winapp\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview.cc(5,10): fatal error C1083: Cannot open include file: 'format': No such file or directory [C:\Users\template\Desktop\temp\winapp\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\template\Desktop\temp\winapp\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview_bridge.cc(6,10): fatal error C1083: Cannot open include file: 'format': No such file or directory [C:\Users\template\Desktop\temp\winapp\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
Building Windows application...
Build process failed.

**Comment by luwei888** [comment]
Update flutter to version 3.7.0

**Comment by hushmand** [comment]
> Update flutter to version 3.7.0

I used Flutter version 3.7.0. But it gave same error

**Comment by Nhsdkk** [comment]
Same on version 3.7.5

**Comment by IvoB1987** [comment]
I have the same issue. Flutter 3.7.5

**Comment by bilalmohammedzeyada** [comment]
I have the same issue
