### ISSUE TITLE
Message Channel

### ISSUE THREAD

**Issue by yisar** [jnschulze/flutter-webview-windows#24]
This is the most important, or is there any alternative, which can communicate between JS and dart?

**Comment by alexmercerind** [comment]
You can already communicate.

**Comment by jnschulze** [comment]
Closing this as it’s already supported.

Thankfully, a user has even published an article with an example: https://codingwithtashi.medium.com/how-to-use-flutter-webview-windows-in-your-flutter-application-and-communicate-between-them-60050f0bb48f
