### ISSUE TITLE
Build error with err LNK2019

### ISSUE THREAD

**Issue by hiepvip99** [jnschulze/flutter-webview-windows#251]
std.ixx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void (__cdecl* std::_Raise_handler)(class stdext::exception const &)" (__imp_?_Raise_handler@std@@3P6AXAEBVexception@stdext@@@ZEA::<!std>) referenced in function "public: void __cdecl stdext::exception::_Raise(void)const " (?_Raise@exception@stdext@@QEBAXXZ::<!std>) [C:\Users\hiepl\Downloads\flutter_poke_com\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\hiepl\Downloads\flutter_poke_com\build\windows\plugins\webview_windows\Debug\webview_windows_plugin.dll : fatal error LNK1120: 1 unresolved externals [C:\Users\hiepl\Downloads\flutter_poke_com\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]

**Comment by kvenkataprasad** [comment]
I am also getting same issue.  but it is working Android & iOS devices not working in windows.
document showing windows 11 OS, but I am working in windows 10 OS environment. 

let us know this library will work in windows 10 environment?
any solution?
