### ISSUE TITLE
showing Unsupported platform on windows 10 enterprise version 2016 LTSB

### ISSUE THREAD

**Issue by lm-chetan** [jnschulze/flutter-webview-windows#257]
![image](https://github.com/jnschulze/flutter-webview-windows/assets/68239699/ec389186-98a7-4163-92cf-ef2caed49afa)

**Comment by tuantiensiu** [comment]
You can check in your window have install `WebView2`,  you can check in your control panel

**Comment by lm-chetan** [comment]
Yes......Webview2 is already installed into my system, You can check below screenshot.

![image](https://github.com/jnschulze/flutter-webview-windows/assets/68239699/80d7847c-1237-43d3-9136-621417808d62)

**Comment by tuantiensiu** [comment]
You can show more error in your debug console

**Comment by jnschulze** [comment]
See https://github.com/jnschulze/flutter-webview-windows/issues/297#issuecomment-2461972934
