### ISSUE TITLE
Cookies Support

### ISSUE THREAD

**Issue by gutisalex** [jnschulze/flutter-webview-windows#26]
Hey, first off, great work... I was looking for webview for windows for some time and the only workaround was using urlservice which opens a browser, etc... But I want to know does that plugin support cookies as well?

**Comment by jnschulze** [comment]
Yes, cookies are supported and are transparently handled by WebView2. This plugin doesn‘t currently provide an API for explicitly managing them.

**Comment by gutisalex** [comment]
ah ok I understand, are you working on managing them via plugin? I have webviews which are behind auth and need sessiontoken, so I need a way to set cookies when loading the webview, like the official webview plugin?!

**Comment by jnschulze** [comment]
It’s not planned, but you might still be able to inject cookies by running `ExecuteScript` and injecting a JavaScript one-liner.
