### ISSUE TITLE
Dropdown Not Working in windows Webview

### ISSUE THREAD

**Issue by divyanshumittal50** [jnschulze/flutter-webview-windows#269]
When choosing webview in windows Not able to open Dropdown ..

**Comment by rjoshi86** [comment]
The issue seems to be with <select> component of angular, all angular sites who has dropdown with <select> tag has issues. Can we please fix this on priority as this is blocker for using most of angular sites inside desktop web view

**Comment by gk-1213** [comment]
element-plus  has same problem
