### ISSUE TITLE
Error: does not contain a CMakeLists.txt file.

### ISSUE THREAD

**Issue by kechankrisna** [jnschulze/flutter-webview-windows#27]
flutter-webview-windows/example/windows/flutter/ephemeral/.plugin_symlinks/webview_windows/windows/third_party/fmt

  does not contain a CMakeLists.txt file.

**Comment by alexmercerind** [comment]
I believe you cloned from the git repository instead of pub.dev.
You need to add `--recursive` flag while cloning the repo.

**Comment by kechankrisna** [comment]
> I believe you cloned from the git repository instead of pub.dev.
> You need to add `--recursive` flag while cloning the repo.

You are absolutely right. now it seems work fine. But I got another error after run app:
 Unhandled Exception: LateInitializationError: Field '_methodChannel@19215898' has not been initialized.

**Comment by alexmercerind** [comment]
@kechankrisna ensure you have Microsoft Edge Webview 2 runtime installed on your machine. 
Download: [Here](https://developer.microsoft.com/en-us/microsoft-edge/webview2/).

**Comment by kechankrisna** [comment]
> @kechankrisna ensure you have Microsoft Edge Webview 2 runtime installed on your machine.
> Download: [Here](https://developer.microsoft.com/en-us/microsoft-edge/webview2/).

I run installed but after that, when run app, it is closed immediately after second.

**Comment by jnschulze** [comment]
> > @kechankrisna ensure you have Microsoft Edge Webview 2 runtime installed on your machine.
> > Download: [Here](https://developer.microsoft.com/en-us/microsoft-edge/webview2/).
> 
> I run installed but after that, when run app, it is closed immediately after second.

Try building without AVX2 (see https://github.com/jnschulze/flutter-webview-windows/issues/25#issuecomment-868733726)

**Comment by kechankrisna** [comment]
> > > @kechankrisna ensure you have Microsoft Edge Webview 2 runtime installed on your machine.
> > > Download: [Here](https://developer.microsoft.com/en-us/microsoft-edge/webview2/).
> > 
> > 
> > I run installed but after that, when run app, it is closed immediately after second.
> 
> Try building without AVX2 (see [#25 (comment)](https://github.com/jnschulze/flutter-webview-windows/issues/25#issuecomment-868733726))

Yes, After commented that lines, it works fine now. But I have one question. Do I need to install  Microsoft Edge Webview 2 runtime in production too?

**Comment by kechankrisna** [comment]
As I read from win32, that is a chance to work with  Microsoft Edge (Chromium).

**Comment by jnschulze** [comment]
Yes. You‘ll either need to ensure that it‘s installed on target device or you need to bundle it with your app somehow (see https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)

**Comment by kechankrisna** [comment]
> Yes. You‘ll either need to ensure that it‘s installed on target device or you need to bundle it with your app somehow (see https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)

This mean, in production, if the user already have pre-installed Microsoft Edge which normally come with windows10, the user doesn't need to install Microsoft Edge Webview 2 runtime, right? Or if wrong, can you show me how to make it possible

**Comment by alexmercerind** [comment]
> can you show me how to make it possible.

Various setup generators for Windows like IONNO setup have settings to include dependency installers. Its currently not supported on MSIX.

**Comment by jnschulze** [comment]
> > Yes. You‘ll either need to ensure that it‘s installed on target device or you need to bundle it with your app somehow (see https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
> 
> This mean, in production, if the user already have pre-installed Microsoft Edge which normally come with windows10, the user doesn't need to install Microsoft Edge Webview 2 runtime, right? Or if wrong, can you show me how to make it possible

According to the linked article, you can‘t rely on the normal Edge (Chromium) Browser in production environments:

„During development and testing, you may use either as the backing web platform.

- The WebView2 Runtime

- Any Insider (non-stable) Microsoft Edge (Chromium) browser channel

In production environments, you must ensure the Runtime is present on user devices before the app starts. The Microsoft Edge Stable channel is unavailable for WebView2 usage. The decision prevents apps from taking a dependency on the browser in production.“
