### ISSUE TITLE
Dropdown box click event has no effect

### ISSUE THREAD

**Issue by gk-1213** [jnschulze/flutter-webview-windows#293]
Open this website using the official demo https://element-plus.org/en-US/component/select.html Dropdown menu click event is invalid

**Comment by ddty2** [comment]
I have the same issue. It also occurs with '<input type="date"...'.

**Comment by sglee487** [comment]
use this package https://github.com/jakky1/webview_win_floating mentioned from this issue https://github.com/jnschulze/flutter-webview-windows/issues/138
