### ISSUE TITLE
Windows application was crashed. Webview not initializing in windows 11 pro.

### ISSUE THREAD

**Issue by Anish-T-GitHub** [jnschulze/flutter-webview-windows#295]
I installed webview2 runtime this webview working in some systems but mostly application was crashed when webview controller initializing time.

OS version - Windows 11 pro
Flutter version - 3.22.2
Dart version - 3.4.3

**Comment by venky9885** [comment]
yes i am also facing same issue

**Comment by venky9885** [comment]
@jnschulze its crashing on windows11 ,please check it ASAP

**Comment by julianbraasch** [comment]
I had that issue too last week, but it was unrelated to my dependencies. Kindly check if your generated output directory contains the necessary Visual C++ Redistributable files as listed [here](https://docs.flutter.dev/platform-integration/windows/building#building-your-own-zip-file-for-windows)

**Comment by venky9885** [comment]
I am building application using msix package,so there's no need to check those files whether they are present.

**Comment by Anish-T-GitHub** [comment]
I fixed this issue 

Please refer this link for issue fix - https://answers.microsoft.com/en-us/windows/forum/all/msvcp140dll-error/b0eaa485-159c-4d66-b12d-ae0e197782e5

need install x64 & x86 redistributables.

then restart you pc.

it works.

**Comment by Alvaro1dev** [comment]
Hi

In my case, I had to downgrade Visual Studio Community 2022 version from 17.10.3 to 17.7.5 to make it work.

**Comment by Anish-T-GitHub** [comment]
> Hi
> 
> In my case, I had to downgrade Visual Studio Community 2022 version from 17.10.3 to 17.7.5 to make it work.

Okay @Alvaro1dev How to downgrade visual studio community 17.7.5.

**Comment by venky9885** [comment]
If I downgrade flutter run doesn't work,so we have to downgrade both flutter and vsiuval studio,I don't want to do

> Hi
> 
> In my case, I had to downgrade Visual Studio Community 2022 version from 17.10.3 to 17.7.5 to make it work.

**Comment by Anish-T-GitHub** [comment]
@venky9885 how to downgrade 17.7.5. i searched the download link but i can't find any link.

**Comment by venky9885** [comment]
Open visuval studio installer then select modify and downgrade it

**Comment by Anish-T-GitHub** [comment]
> If I downgrade flutter run doesn't work,so we have to downgrade both flutter and vsiuval studio,I don't want to do
> 
> > Hi
> > In my case, I had to downgrade Visual Studio Community 2022 version from 17.10.3 to 17.7.5 to make it work.

Yes @venky9885 i downgrade visual studio to 17.7.5 it's working for me and build was getting successfully without any issues. I used latest flutter version i dinn't getting any errors. Thank You @Alvaro1dev.

Flutter Framework Details
================
OS version - Windows 11 pro
Flutter version - 3.22.2
Dart version - 3.4.3

**Comment by venky9885** [comment]
Don`t close this we need perfect solution in new versions of software
Flutter latest version  as well visuval studio communtity
