### ISSUE TITLE
windows server 2016 unsupported_plaform

### ISSUE THREAD

**Issue by JemmyWang94** [jnschulze/flutter-webview-windows#297]
windows server 2016
code: unsupported_plaform
Message: The plaform is not supported

Webview2 Official documents supports windows server 2016, and i have tried other plug-in([webview_win_floating](https://pub-web.flutter-io.cn/packages/webview_win_floating)), it can work. 

Can you update your code to support windows server 2016(windows10 1607) @tlercher @jnschulze @jgoyvaerts @brownson @Doflatango

**Comment by JemmyWang94** [comment]
Or could you explain why Windows server2016 cannot support the Win10 1607 kernel, as it is supported on the Webview2 official website.
https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/

**Comment by jnschulze** [comment]
As @czw299 already pointed out, `Windows.Graphics.Capture` requires at least Windows 10 1809.
