### ISSUE TITLE
Not rum 

### ISSUE THREAD

**Issue by fabio21** [jnschulze/flutter-webview-windows#3]
path configured ok
NuGet

CMake Error at flutter/ephemeral/.plugin_symlinks/webview_windows/windows/CMakeLists.txt:9 (add_subdirectory):
  The source directory

    C:/dart_templetes/flutter-webview-windows/example/windows/flutter/ephemeral/.plugin_symlinks/webview_windows/windows/third_party/fmt

  does not contain a CMakeLists.txt file.

NUGET.EXE not found.
CMake Error at flutter/ephemeral/.plugin_symlinks/webview_windows/windows/CMakeLists.txt:14 (message):
  Please install this executable, and run CMake again.

Exception: Unable to generate build files

**Comment by fabio21** [comment]
Thank you works! git submodule init && git submodule update
But I can't rotate here


`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\dart_templetes\flutter_app\build\windows\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmErrorLevel [C:\dart_templetes\flutter_app\build\windows\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: exit /b %1 [C:\dart_templetes\flutter_app\build\windows\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmDone [C:\dart_templetes\flutter_app\build\windows\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [C:\dart_templetes\flutter_app\build\windows\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :VCEnd" foi encerrado com o código 1. [C:\dart_templetes\flutter_app\build\windows\INSTALL.vcxproj]
Exception: Build process failed.`

In Visual Studio this error

`Severity Code	Description Project	File Line Suppression State Error 
CMake Error at C:\dart_templetes\flutter-webview-windows\windows\CMakeLists.txt:36 
(apply_standard_settings):  Unknown CMake command "apply_standard_settings".	
C:\dart_templetes\flutter-webview-windows\windows\CMakeLists.txt	36	
`

**Comment by chongbo2013** [comment]
flutter clean
