### ISSUE TITLE
Navigation webview

### ISSUE THREAD

**Issue by muhammadsaddamnur** [jnschulze/flutter-webview-windows#32]
How to navigate (back/forward) ?

**Comment by jnschulze** [comment]
It's not implemented yet.
You'd need to extend the WebviewController on the dart side and plumb it to [GoForward](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.864.35#goforward) / [GoBack](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.864.35#goback) on the native side.

**Comment by jnschulze** [comment]
It's implemented now (see #33)
