### ISSUE TITLE
Mouse Down on DropdownList not showing anymore.

### ISSUE THREAD

**Issue by toannguyendts** [jnschulze/flutter-webview-windows#37]
Some functions cannot work
1/When we are using some dropdownlist such as Select2 : https://select2.org/getting-started/basic-usage . We clicked Dropdown and it did not show.  
2/ Scroll not work for jQuery Scrollbar : https://gromo.github.io/jquery.scrollbar/demo/basic.html
Hope to receive your feedback soon @jnschulze . Thank you!

**Comment by njuptzwt** [comment]
Hello, do you have any idea of the Dropdown list? Have you solved it?

**Comment by njuptzwt** [comment]
> Some functions cannot work 1/When we are using some dropdownlist such as Select2 : https://select2.org/getting-started/basic-usage . We clicked Dropdown and it did not show. 2/ Scroll not work for jQuery Scrollbar : https://gromo.github.io/jquery.scrollbar/demo/basic.html Hope to receive your feedback soon @jnschulze . Thank you!
Do you know how to solve the dropdownlist?

**Comment by njuptzwt** [comment]
@toannguyendts

**Comment by njuptzwt** [comment]
@toannguyendts Do you know how to solve the dropdownlist?
