### ISSUE TITLE
error running the project

### ISSUE THREAD

**Issue by maxTeste** [jnschulze/flutter-webview-windows#42]
just downloaded the project and it's not running.....
(No implementation found for method initialize on channel io.jns.webview.win)

![image](https://user-images.githubusercontent.com/75133022/130415593-5740c5c0-33b2-447f-b355-a362dfd1f24d.png)

**Comment by jnschulze** [comment]
What do you mean by "downloaded"? Just add `webview_windows: ^0.0.7` to your pubspec.

**Comment by maxTeste** [comment]
downloaded the project on the repository, the example project supposedly working with the plugin and already try to add webview_windows: ^0.0.7 to my pubspec and both didn't work....

**Comment by sunlunchang1994** [comment]
i have the same problem

**Comment by jnschulze** [comment]
This is usually caused by the WebView runtime not being installed.
