### ISSUE TITLE
Any chance you could push a new release?

### ISSUE THREAD

**Issue by jgoyvaerts** [jnschulze/flutter-webview-windows#44]
There's some changes on main which haven't made it to pub.dev yet. When using the git pubspec.yaml approach to get the latest commit, pubspec.yaml doesn't clone the repo with submodules so you get a cmake build error when building windows in release mode.

If you could push a new release to pubspec.yaml we could go back to using the normal pubspec way again.

Issue that pubspec yaml doesn't clone submodules: https://github.com/dart-lang/pub/issues/2807
Cmake build error issue: https://github.com/jnschulze/flutter-webview-windows/issues/27

**Comment by jnschulze** [comment]
Sorry for the inconvenience. I will publish a new version today.

**Comment by jnschulze** [comment]
Done.
