### ISSUE TITLE
Read HTML from webview

### ISSUE THREAD

**Issue by dodatw** [jnschulze/flutter-webview-windows#45]
Is it possiable read html when page finished ?

We implement the same function on flutter_webview
```
return WebView(
 ...
    onPageFinished: (result) async {
      String html =
      (await _mobileWebViewController!.evaluateJavascript(
          "window.document.getElementsByTagName('html')[0].outerHTML;"));
      //read(html);
    },
 ...
}
```

Thanks~

**Comment by jnschulze** [comment]
Yes, you can post a message from JavaScript to Dart.

**Comment by dodatw** [comment]
@jnschulze could you explain more detail?

How to grab HTML by javaScript?
Note, the target website is not mine, (ex, https://flutter.dev/)

**Comment by jnschulze** [comment]
- The webview controller exposes a `Stream<LoadingState>` that allows you to get notified once loading completes.
- There’s `executeScript` to run a script for reading the HTML and posting a message back to the Dart side.

**Comment by dodatw** [comment]
I implement like this:
```
    _winWebViewController!.loadingState.listen((event) {
      if(event == window_web.LoadingState.navigationCompleted) {
        _winWebViewController!.executeScript("window.document.getElementsByTagName('html')[0].outerHTML;");
        // how to "posting a message back to the Dart side" ?
      }
    });
```

executeScript is a Future<void>, not like Future<String> evaluateJavascript

**Comment by jnschulze** [comment]
This won't work. You need to post the return value of `window.document.getElementsByTagName('html')[0].outerHTML` as a message back to Flutter. See the linked medium article.

**Comment by dodatw** [comment]
did you mean I need to implement sendDataToFlutter in website?
But website is not mine
```
function sendDataToFlutter() {
  var value = {"name":"tashi"}
  window.chrome.webview.postMessage(value);

}
```

**Comment by jnschulze** [comment]
No, You can still put the whole script into one single string that gets passed to `executeScript`....

**Comment by dodatw** [comment]
@jnschulze I have no idea how to do this, I want to read string after call `executeScript`, but it return `void`.
Anyway, Thank your support.

**Comment by jnschulze** [comment]
> @jnschulze I have no idea how to do this, I want to read string after call `executeScript`, but it return `void`.

Yes, `executeScript` won’t return data, so have your code post a message:
`executeScript('window.chrome.webview.postMessage(...)')`
