### ISSUE TITLE
build run error

### ISSUE THREAD

**Issue by lq7y7-go** [jnschulze/flutter-webview-windows#47]
--- stderr
  CMake Error at flutter/webview_windows/CMakeLists.txt:32 (message):
    Integrity check for
    D:/flutter_qtalk/target/debug/build/qtalk_x-33ced172032e5b70/out/build/nuget.exe
    failed

**Comment by FN8087** [comment]
我也遇到同样的问题

**Comment by FN8087** [comment]
> --- flutter/webview_windows/CMakeLists.txt:32 处的stderr CMake 错误（消息）： D:/flutter_qtalk/target/debug/build/qtalk_x-33ced172032e5b70/out/build/nuget.exe 的 完整性检查 失败

请问解决了？

**Comment by lq7y7-go** [comment]
no

**Comment by jnschulze** [comment]
See #88.

**Comment by jinfagang** [comment]
@jnschulze  Please, I beg you, don't insert nuget in cmake....

<img width="172" alt="image" src="https://user-images.githubusercontent.com/21303438/219951417-fae40622-f04d-4f4b-9e2d-7e33afacaa74.png">

<img width="555" alt="image" src="https://user-images.githubusercontent.com/21303438/219951435-78e4afd8-a5cb-4d2c-bbfb-bef37acfe5ab.png">


I download this 6.4M thing need 8 hours.... in China...

Please, stop insert nuget in cmake...
