### ISSUE TITLE
Error on _webMessageStreamController (webview_windows)

### ISSUE THREAD

**Issue by PREVOTGilles** [jnschulze/flutter-webview-windows#51]
In the file webview_windows.dart
when I send a message from HTML/Javascript page (window.chrome.webview.postMessage("WebTask::Decrement Counter");)
I receive the message and process it in 
line 212  _eventChannel.receiveBroadcastStream().listen((event) {.......    
               ........
               ........
line 238    final message = json.decode(map['value']);
line 239     _webMessageStreamController.add(message);
I got this error:

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'String' is not a subtype of type 'Map<dynamic, dynamic>'
#0      WebviewController.initialize.<anonymous closure> (package:webview_windows/webview_windows.dart:239:49)
.........

**Comment by jnschulze** [comment]
Try posting a JSON object as opposed to a string.
