### ISSUE TITLE
Browser may not be secure when authenticating via google

### ISSUE THREAD

**Issue by AhyaanTech** [jnschulze/flutter-webview-windows#66]
Hi! Amazing Package! thankyou!

Im trying to use this package to implement an oauth flow.
After users are redirected to google auth. google informs that the browser may not be secure and does not let the user log in.

https://user-images.githubusercontent.com/76003859/146657999-86f94b54-6f59-4d9b-95b5-af8bca8df1ee.mp4

Hopefully the attachment is good enuff to show what i mean.

P.S.
How do i close the webview? _controller.dispose() ?

**Comment by AhyaanTech** [comment]
Unfortunate. since this is something we can't do anything about. ill close this ticket.

**Comment by jarno9981** [comment]
> Unfortunate. since this is something we can't do anything about. ill close this ticket.

Change useragent #1647

That will fix auth

**Comment by AhyaanTech** [comment]
@jarno9981 i did not quite understand. I humbly request a code example.

**Comment by AhyaanTech** [comment]
https://codelabs.developers.google.com/codelabs/flutter-github-graphql-client#3 also this code lab shows a different way to achieve oauth flow if webview alternate is required.

**Comment by jarno9981** [comment]
@AhyaanTech   

Exact code we use with webview2 google auth

private string originalUserAgent = "";
private void webView_NavigationStarting(object sender, CoreWebView2NavigationStartingEventArgs e) {
            if (new Uri(e.Uri).Host.Contains("accounts.google.com")) {
                if (webView.CoreWebView2 != null) {
                    var settings = webView.CoreWebView2.Settings;
                    if (settings.UserAgent != "Chrome")
                        originalUserAgent = settings.UserAgent;

                    settings.UserAgent = "Chrome";
                }
            } else {
                if (webView.CoreWebView2 != null) {
                    var settings = webView.CoreWebView2.Settings;
                    if (settings.UserAgent == "Chrome")
                        settings.UserAgent = originalUserAgent;
                }
            }
        }
