### ISSUE TITLE
Location of Folder MyApp.exe.WebView2 should be configurable

### ISSUE THREAD

**Issue by brownson** [jnschulze/flutter-webview-windows#7]
The folder MyApp.exe.WebView2 is automatically created in the location of flutter application.

If the application is installed in the Program Dirctory of Windows, the app has no write access to this folder.

There shoud be an option to configure the location of the folder or the default location should be somewhere else (eg should be located in %appdata%)

**Comment by jnschulze** [comment]
Done. By calling 
`await WebviewController.initializeEnvironment(userDataPath: "my/custom/path");`
before creating any WebView instance, you can take control of the user data directory.

Note that I've changed the default directory, too. It now defaults to `%APPDATA%\Roaming\flutter_webview_windows\YourExecutableNameWithoutExtension`

**Comment by brownson** [comment]
Thanks for the feature - I know there is no official version, but should I be already able to use it?

When I try to build the windows application, I get the following error:

```
CMake Error at flutter/ephemeral/.plugin_symlinks/webview_windows/windows/CMakeLists.txt:21 (add_subdirectory):
  The source directory

    .../windows/flutter/ephemeral/.plugin_symlinks/webview_windows/windows/third_party/fmt

  does not contain a CMakeLists.txt file.
```

**Comment by jnschulze** [comment]
> When I try to build the windows application, I get the following error:
> 
> ```
> CMake Error at flutter/ephemeral/.plugin_symlinks/webview_windows/windows/CMakeLists.txt:21 (add_subdirectory):
>   The source directory
> 
>     .../windows/flutter/ephemeral/.plugin_symlinks/webview_windows/windows/third_party/fmt
> 
>   does not contain a CMakeLists.txt file.
> ```

Did you install it from [pub.dev](https://pub.dev/packages/webview_windows) or did you clone it manually?
Looks like `third_party/fmt` didn‘t get ckecked out. So please use `git clone --recursive` or check out submodules after cloning.

**Comment by brownson** [comment]
Thanks, it works now :)
