### ISSUE TITLE
How to use the microphone and webcam in the viewer

### ISSUE THREAD

**Issue by Tzanou123** [jnschulze/flutter-webview-windows#81]
Hello,

Im trying to use website who need to use the microphone and webcam access in the webview is this possible to achieve that ?

Thanks

**Comment by jnschulze** [comment]
Hi,
yes, the example shows how to add a custom permission handler.
It will get invoked once the Webview tries to access the webcam, microphone etc.
You can either show a custom dialog or just always grant permission.

**Comment by Tzanou123** [comment]
Thanks a lot it is working like a charm !
