### ISSUE TITLE
Is there equivalent of flutter_webview addJavaScriptHandler

### ISSUE THREAD

**Issue by Tzanou123** [jnschulze/flutter-webview-windows#83]
Hello,

In Flutter_weview dependency i can add a javascript handler by calling addJavaScriptHandler function from controller ! can i achieve this with flutter-webview-windows ?

Thanks

**Comment by jnschulze** [comment]
There’s only `executeScript` ATM.

**Comment by Tzanou123** [comment]
whats about addListener() do you have any example of use ?

**Comment by jnschulze** [comment]
`executeScript` doesn’t return a value but you can post a message containing the innerHTML back to Dart. 

See https://codingwithtashi.medium.com/how-to-use-flutter-webview-windows-in-your-flutter-application-and-communicate-between-them-60050f0bb48f
