### ISSUE TITLE
Crash on windows 11 Pro

### ISSUE THREAD

**Issue by bryanburress** [jnschulze/flutter-webview-windows#85]
Example from pub.dev to include custom widget build crashes on open in Windows 11 Pro 21H2  22000.434 after release Build. Android Studio renders application with no issue, however after running "flutter build windows" app crashes as soon as widget loads.

**Comment by jnschulze** [comment]
Debugging release builds can be tricky, but first of all, you should look for a corresponding entry at the Windows event log (eventvwr).
Try to run your project’s Flutter runner solution in Visual Studio in release mode (see https://docs.microsoft.com/en-us/cpp/build/how-to-debug-a-release-build?view=msvc-170). If the app crashes again, you should see the issue immediately. If not, open the VS disassembler view and jump to the fault offset from the event viewer entry.

**Comment by jnschulze** [comment]
Should be fixed in v0.1.5.
