### ISSUE TITLE
flutter app run error. exception code is 0xc0000001d.

### ISSUE THREAD

**Issue by Ko-JoonYoung** [jnschulze/flutter-webview-windows#93]
I can't run the flutter app using the webview_windows plugin on my test device.
test device spec is
 - cpu : intel celeron CPU G3930 @ 2.90GHz
 - ram: 4GB
 - os: Windows 10 Enterprise (21H2)

already installed webview2 runtime.

Could someone please tell me about this?
thank you.

**Comment by Ko-JoonYoung** [comment]
Does the CPU have to support AVX?

**Comment by jnschulze** [comment]
It should detect presence of AVX2 at runtime but you can try to comment out
`target_compile_options(${PLUGIN_NAME} PRIVATE "/arch:AVX2")`
In `windows/CMakeLists.txt`

**Comment by Ko-JoonYoung** [comment]
@jnschulze 
Thank you for your comment. It's like an oasis in the desert.

Does that mean it can't run without AVX support?

I have never used cmakelist before.

# Compilation settings that should be applied to most targets.
function(APPLY_STANDARD_SETTINGS TARGET)
  target_compile_features(${TARGET} PUBLIC cxx_std_17)
  target_compile_options(${TARGET} PRIVATE /W4 /WX /wd"4100")
  target_compile_options(${TARGET} PRIVATE /EHsc)
  **target_compile_options(${TARGET} PRIVATE "/arch:AVX2")**
  target_compile_definitions(${TARGET} PRIVATE "_HAS_EXCEPTIONS=0")
  target_compile_definitions(${TARGET} PRIVATE "$<$<CONFIG:Debug>:_DEBUG>")
endfunction()

In this case, windows app is not run without any error.

**Comment by Ko-JoonYoung** [comment]
Thank you for your comment.
It is resolved.

**Comment by Ko-JoonYoung** [comment]
I have one more question.
If I try to comment out that, CPU usage will be 100%.
Is the problem caused by not using AVX?
