### ISSUE TITLE
system full screen

### ISSUE THREAD

**Issue by mabDc** [jnschulze/flutter-webview-windows#98]
when play video request full screen, there is only fill the container, but not the window or the system

**Comment by jnschulze** [comment]
This requires forwarding of `containsFullScreenElementChanged` to the Dart side (see https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.1108.44#add_containsfullscreenelementchanged)

**Comment by mabDc** [comment]
i found anothor package [window_manager](https://pub.dev/packages/window_manager) solve my problem

**Comment by tuantiensiu** [comment]
I have to same request

**Comment by Mhamad-Rzgar** [comment]
> 

Hi @jnschulze can you show me how to detect that element trigger full screen please, or how to use this containsFullScreenElementChanged event handler with your package?

thank you.
